"""add_user_profile_fields

Revision ID: 09732fefc9e6
Revises: 612dc9933fce
Create Date: 2026-02-05 05:27:04.030640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09732fefc9e6'
down_revision = '612dc9933fce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(), nullable=True))
    op.add_column('users', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('users', sa.Column('skills', sa.String(), nullable=True))
    op.add_column('users', sa.Column('linkedin_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('portfolio_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_locations', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'preferred_locations')
    op.drop_column('users', 'portfolio_url')
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'industry')
    op.drop_column('users', 'company')
    op.drop_column('users', 'job_title')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
