"""make_first_published_nullable

Revision ID: 118e70bf1e49
Revises: e93348b3f779
Create Date: 2026-02-17 03:43:29.614633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '118e70bf1e49'
down_revision = 'e93348b3f779'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('greenhouse_job_metadata', 'first_published',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('greenhouse_job_metadata', 'first_published',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
