"""make_requisition_id_nullable

Revision ID: 54caf0054c9e
Revises: fa470ef03d54
Create Date: 2026-02-20 18:48:51.246387

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "54caf0054c9e"
down_revision = "fa470ef03d54"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "greenhouse_job_metadata", "requisition_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_index(op.f("idx_jobs_search_vector"), table_name="jobs", postgresql_using="gin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_jobs_search_vector"),
        "jobs",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.alter_column(
        "greenhouse_job_metadata", "requisition_id", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
