"""add_hashed_password_to_users

Revision ID: 612dc9933fce
Revises: 20260204_225527
Create Date: 2026-02-05 05:12:27.428260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612dc9933fce'
down_revision = '20260204_225527'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sessions_token_key'), 'sessions', type_='unique')
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(op.f('verification_tokens_token_key'), 'verification_tokens', type_='unique')
    op.drop_index(op.f('ix_verification_tokens_token'), table_name='verification_tokens')
    op.create_index(op.f('ix_verification_tokens_token'), 'verification_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_tokens_token'), table_name='verification_tokens')
    op.create_index(op.f('ix_verification_tokens_token'), 'verification_tokens', ['token'], unique=False)
    op.create_unique_constraint(op.f('verification_tokens_token_key'), 'verification_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'hashed_password')
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=False)
    op.create_unique_constraint(op.f('sessions_token_key'), 'sessions', ['token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
