"""make_ashby_metadata_nullable

Revision ID: a9470a9285c7
Revises: c89466e23466
Create Date: 2026-02-20 20:56:48.266578

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a9470a9285c7"
down_revision = "c89466e23466"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ashby_job_metadata", "department", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("ashby_job_metadata", "team", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "ashby_job_metadata", "employment_type", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("ashby_job_metadata", "location_raw", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "ashby_job_metadata", "address_locality", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "ashby_job_metadata", "address_region", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "ashby_job_metadata", "address_country", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "ashby_job_metadata", "description_html", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "ashby_job_metadata", "description_plain", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "ashby_job_metadata",
        "compensation",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "ashby_job_metadata",
        "is_listed",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ashby_job_metadata",
        "is_listed",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "ashby_job_metadata",
        "compensation",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "ashby_job_metadata", "description_plain", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "ashby_job_metadata", "description_html", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "ashby_job_metadata", "address_country", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "ashby_job_metadata", "address_region", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "ashby_job_metadata", "address_locality", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "ashby_job_metadata", "location_raw", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "ashby_job_metadata", "employment_type", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("ashby_job_metadata", "team", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("ashby_job_metadata", "department", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
