"""make_lever_metadata_nullable

Revision ID: c89466e23466
Revises: 54caf0054c9e
Create Date: 2026-02-20 20:43:04.410371

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c89466e23466"
down_revision = "54caf0054c9e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("lever_job_metadata", "commitment", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("lever_job_metadata", "department", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("lever_job_metadata", "team", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("lever_job_metadata", "team", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("lever_job_metadata", "department", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("lever_job_metadata", "commitment", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
