"""drop classification retry columns

Revision ID: e4b631307fbe
Revises: 9d71b1e8a4c2
Create Date: 2026-02-24 22:18:39.003020

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "e4b631307fbe"
down_revision = "9d71b1e8a4c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_applied_jobs_job_id"), table_name="applied_jobs")
    op.drop_index(op.f("ix_applied_jobs_user_id"), table_name="applied_jobs")
    op.drop_index(op.f("ix_jobs_classification_next_retry_at"), table_name="jobs")
    op.drop_index(op.f("ix_saved_jobs_job_id"), table_name="saved_jobs")
    op.drop_index(op.f("ix_saved_jobs_user_id"), table_name="saved_jobs")
    op.drop_index(op.f("ix_user_notifications_user_id"), table_name="user_notifications")
    # ### end Alembic commands ###

    # Drop classification retry columns
    op.drop_column("jobs", "classification_attempts")
    op.drop_column("jobs", "classification_last_attempt_at")
    op.drop_column("jobs", "classification_next_retry_at")
    op.drop_column("jobs", "classification_last_error")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_user_notifications_user_id"), "user_notifications", ["user_id"], unique=False
    )
    op.create_index(op.f("ix_saved_jobs_user_id"), "saved_jobs", ["user_id"], unique=False)
    op.create_index(op.f("ix_saved_jobs_job_id"), "saved_jobs", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_jobs_classification_next_retry_at"),
        "jobs",
        ["classification_next_retry_at"],
        unique=False,
    )
    op.create_index(op.f("ix_applied_jobs_user_id"), "applied_jobs", ["user_id"], unique=False)
    op.create_index(op.f("ix_applied_jobs_job_id"), "applied_jobs", ["job_id"], unique=False)
    # ### end Alembic commands ###
