"""change_internal_job_id_to_bigint

Revision ID: e93348b3f779
Revises: e6f9f27a2c47
Create Date: 2026-02-17 03:31:36.045223

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e93348b3f779"
down_revision = "e6f9f27a2c47"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "greenhouse_job_metadata",
        "internal_job_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "greenhouse_job_metadata",
        "internal_job_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
