"""add_user_notes_and_last_login

Revision ID: e940925df339
Revises: 2c9d90bafa94
Create Date: 2026-02-22 20:22:46.172628

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e940925df339"
down_revision = "2c9d90bafa94"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_login_at")
    op.drop_column("users", "notes")
    # ### end Alembic commands ###
