"""Geographic constants for location parsing and cleanup."""

from __future__ import annotations

import re
from typing import Final, Pattern

COUNTRY_UNITED_STATES: Final[str] = "United States"
COUNTRY_UNITED_KINGDOM: Final[str] = "United Kingdom"
COUNTRY_SOUTH_KOREA: Final[str] = "South Korea"
COUNTRY_TURKEY: Final[str] = "Turkey"
COUNTRY_CZECHIA: Final[str] = "Czechia"
COUNTRY_INDIA: Final[str] = "India"
COUNTRY_GERMANY: Final[str] = "Germany"
COUNTRY_FRANCE: Final[str] = "France"
COUNTRY_CHINA: Final[str] = "China"
COUNTRY_JAPAN: Final[str] = "Japan"
COUNTRY_CANADA: Final[str] = "Canada"
COUNTRY_AUSTRALIA: Final[str] = "Australia"
COUNTRY_NETHERLANDS: Final[str] = "Netherlands"
COUNTRY_UAE: Final[str] = "United Arab Emirates"

COUNTRIES: Final[frozenset[str]] = frozenset(
    {
        "Afghanistan",
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Argentina",
        "Armenia",
        COUNTRY_AUSTRALIA,
        "Austria",
        "Azerbaijan",
        "Bahrain",
        "Bangladesh",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bhutan",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Botswana",
        "Brazil",
        "Brunei",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cambodia",
        "Cameroon",
        COUNTRY_CANADA,
        "Cape Verde",
        "Central African Republic",
        "Chad",
        "Chile",
        COUNTRY_CHINA,
        "Colombia",
        "Comoros",
        "Congo",
        "Costa Rica",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czech Republic",
        COUNTRY_CZECHIA,
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Eswatini",
        "Ethiopia",
        "Fiji",
        "Finland",
        COUNTRY_FRANCE,
        "Gabon",
        "Gambia",
        "Georgia",
        COUNTRY_GERMANY,
        "Ghana",
        "Greece",
        "Grenada",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Honduras",
        "Hungary",
        "Iceland",
        COUNTRY_INDIA,
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy",
        "Jamaica",
        COUNTRY_JAPAN,
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Kosovo",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macedonia",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Mauritania",
        "Mauritius",
        "Mexico",
        "Micronesia",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        COUNTRY_NETHERLANDS,
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "North Korea",
        "North Macedonia",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Palestine",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Qatar",
        "Romania",
        "Russia",
        "Rwanda",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        COUNTRY_SOUTH_KOREA,
        "South Sudan",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Swaziland",
        "Sweden",
        "Switzerland",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "Timor-Leste",
        "Togo",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        COUNTRY_TURKEY,
        "Turkmenistan",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        COUNTRY_UAE,
        COUNTRY_UNITED_KINGDOM,
        COUNTRY_UNITED_STATES,
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Vatican City",
        "Venezuela",
        "Vietnam",
        "Yemen",
        "Zambia",
        "Zimbabwe",
    }
)

COUNTRY_ALIASES: Final[dict[str, str]] = {
    "us": COUNTRY_UNITED_STATES,
    "usa": COUNTRY_UNITED_STATES,
    "u.s": COUNTRY_UNITED_STATES,
    "u.s.": COUNTRY_UNITED_STATES,
    "uk": COUNTRY_UNITED_KINGDOM,
    "gb": COUNTRY_UNITED_KINGDOM,
    "uae": COUNTRY_UAE,
    "türkiye": COUNTRY_TURKEY,
    "turkiye": COUNTRY_TURKEY,
    "korea": COUNTRY_SOUTH_KOREA,
    "korea, republic of": COUNTRY_SOUTH_KOREA,
    "republic of korea": COUNTRY_SOUTH_KOREA,
    "the netherlands": COUNTRY_NETHERLANDS,
    "russian federation": "Russia",
    "czech republic": COUNTRY_CZECHIA,
}

COUNTRIES_AS_CITIES: Final[frozenset[str]] = frozenset(
    {
        "afghanistan",
        "albania",
        "algeria",
        "andorra",
        "angola",
        "antarctica",
        "argentina",
        "armenia",
        "australia",
        "austria",
        "azerbaijan",
        "bahrain",
        "bangladesh",
        "belarus",
        "belgium",
        "belize",
        "benin",
        "bhutan",
        "bolivia",
        "bosnia",
        "bosnia and herzegovina",
        "botswana",
        "brazil",
        "brunei",
        "bulgaria",
        "burkina faso",
        "burundi",
        "cambodia",
        "cameroon",
        "canada",
        "cape verde",
        "central african republic",
        "chad",
        "chile",
        "china",
        "colombia",
        "comoros",
        "congo",
        "costa rica",
        "croatia",
        "cuba",
        "cyprus",
        "czech republic",
        "czechia",
        "denmark",
        "djibouti",
        "dominica",
        "dominican republic",
        "ecuador",
        "egypt",
        "el salvador",
        "equatorial guinea",
        "eritrea",
        "estonia",
        "eswatini",
        "ethiopia",
        "fiji",
        "finland",
        "france",
        "gabon",
        "gambia",
        "georgia",
        "germany",
        "ghana",
        "greece",
        "grenada",
        "guatemala",
        "guinea",
        "guinea-bissau",
        "guyana",
        "haiti",
        "honduras",
        "hungary",
        "iceland",
        "india",
        "indonesia",
        "iran",
        "iraq",
        "ireland",
        "israel",
        "italy",
        "jamaica",
        "japan",
        "jordan",
        "kazakhstan",
        "kenya",
        "kiribati",
        "korea",
        "kosovo",
        "kuwait",
        "kyrgyzstan",
        "laos",
        "latvia",
        "lebanon",
        "lesotho",
        "liberia",
        "libya",
        "liechtenstein",
        "lithuania",
        "luxembourg",
        "macedonia",
        "madagascar",
        "malawi",
        "malaysia",
        "maldives",
        "mali",
        "malta",
        "marshall islands",
        "mauritania",
        "mauritius",
        "mexico",
        "micronesia",
        "moldova",
        "monaco",
        "mongolia",
        "montenegro",
        "morocco",
        "mozambique",
        "myanmar",
        "namibia",
        "nauru",
        "nepal",
        "netherlands",
        "new zealand",
        "nicaragua",
        "niger",
        "nigeria",
        "north korea",
        "north macedonia",
        "norway",
        "oman",
        "pakistan",
        "palau",
        "palestine",
        "panama",
        "papua new guinea",
        "paraguay",
        "peru",
        "philippines",
        "poland",
        "portugal",
        "qatar",
        "romania",
        "russia",
        "rwanda",
        "saint kitts and nevis",
        "saint lucia",
        "saint vincent and the grenadines",
        "samoa",
        "san marino",
        "sao tome and principe",
        "saudi arabia",
        "senegal",
        "serbia",
        "seychelles",
        "sierra leone",
        "singapore",
        "slovakia",
        "slovenia",
        "solomon islands",
        "somalia",
        "south africa",
        "south korea",
        "south sudan",
        "spain",
        "sri lanka",
        "sudan",
        "suriname",
        "swaziland",
        "sweden",
        "switzerland",
        "syria",
        "taiwan",
        "tajikistan",
        "tanzania",
        "thailand",
        "timor-leste",
        "togo",
        "tonga",
        "trinidad and tobago",
        "tunisia",
        "turkey",
        "turkmenistan",
        "tuvalu",
        "uganda",
        "ukraine",
        "united arab emirates",
        "uae",
        "united kingdom",
        "uk",
        "united states",
        "us",
        "usa",
        "uruguay",
        "uzbekistan",
        "vanuatu",
        "vatican city",
        "venezuela",
        "vietnam",
        "yemen",
        "zambia",
        "zimbabwe",
        "africa",
        "asia",
        "europe",
        "north america",
        "south america",
        "oceania",
        "latin america",
        "central america",
        "caribbean",
        "middle east",
        "european union",
        "americas",
    }
)

US_STATE_ABBREVIATIONS: Final[frozenset[str]] = frozenset(
    {
        "AL",
        "AK",
        "AZ",
        "AR",
        "CA",
        "CO",
        "CT",
        "DE",
        "FL",
        "GA",
        "HI",
        "ID",
        "IL",
        "IN",
        "IA",
        "KS",
        "KY",
        "LA",
        "ME",
        "MD",
        "MA",
        "MI",
        "MN",
        "MS",
        "MO",
        "MT",
        "NE",
        "NV",
        "NH",
        "NJ",
        "NM",
        "NY",
        "NC",
        "ND",
        "OH",
        "OK",
        "OR",
        "PA",
        "RI",
        "SC",
        "SD",
        "TN",
        "TX",
        "UT",
        "VT",
        "VA",
        "WA",
        "WV",
        "WI",
        "WY",
        "DC",
    }
)

STATES_AS_CITIES: Final[frozenset[str]] = frozenset(
    {
        "alabama",
        "alaska",
        "arizona",
        "arkansas",
        "california",
        "colorado",
        "connecticut",
        "delaware",
        "florida",
        "georgia",
        "hawaii",
        "idaho",
        "illinois",
        "indiana",
        "iowa",
        "kansas",
        "kentucky",
        "louisiana",
        "maine",
        "maryland",
        "massachusetts",
        "michigan",
        "minnesota",
        "mississippi",
        "missouri",
        "montana",
        "nebraska",
        "nevada",
        "new hampshire",
        "new jersey",
        "new mexico",
        "new york",
        "north carolina",
        "north dakota",
        "ohio",
        "oklahoma",
        "oregon",
        "pennsylvania",
        "rhode island",
        "south carolina",
        "south dakota",
        "tennessee",
        "texas",
        "utah",
        "vermont",
        "virginia",
        "washington",
        "west virginia",
        "wisconsin",
        "wyoming",
        "district of columbia",
        "puerto rico",
        "alberta",
        "british columbia",
        "manitoba",
        "new brunswick",
        "newfoundland and labrador",
        "nova scotia",
        "ontario",
        "prince edward island",
        "quebec",
        "saskatchewan",
        "yukon",
        "northwest territories",
        "nunavut",
        "england",
        "scotland",
        "wales",
        "northern ireland",
        "andhra pradesh",
        "arunachal pradesh",
        "assam",
        "bihar",
        "chhattisgarh",
        "goa",
        "gujarat",
        "haryana",
        "himachal pradesh",
        "jharkhand",
        "karnataka",
        "kerala",
        "madhya pradesh",
        "maharashtra",
        "manipur",
        "meghalaya",
        "mizoram",
        "nagaland",
        "odisha",
        "punjab",
        "rajasthan",
        "sikkim",
        "tamil nadu",
        "telangana",
        "tripura",
        "uttar pradesh",
        "uttarakhand",
        "west bengal",
        "delhi",
        "new south wales",
        "victoria",
        "queensland",
        "south australia",
        "western australia",
        "tasmania",
        "australian capital territory",
        "northern territory",
        "bavaria",
        "baden-wurttemberg",
        "brandenburg",
        "hesse",
        "lower saxony",
        "mecklenburg-vorpommern",
        "north rhine-westphalia",
        "rhineland-palatinate",
        "saarland",
        "saxony",
        "saxony-anhalt",
        "schleswig-holstein",
        "thuringia",
        "flanders",
        "wallonia",
        "catalonia",
        "basque country",
        "galicia",
        "andalusia",
        "ile-de-france",
        "brittany",
        "normandy",
        "provence-alpes-cote d'azur",
        "occitanie",
        "hauts-de-france",
        "grand est",
        "pays de la loire",
        "auvergne-rhone-alpes",
        "aquitaine",
        "greater london",
        "greater london area",
        "greater manchester",
        "berkshire",
        "hampshire",
        "surrey",
        "kent",
        "essex",
        "middlesex",
        "lancashire",
        "yorkshire",
        "cheshire",
        "hertfordshire",
        "buckinghamshire",
        "oxfordshire",
        "cambridgeshire",
        "devon",
        "cornwall",
        "somerset",
        "dorset",
        "wiltshire",
        "gloucestershire",
        "warwickshire",
        "northamptonshire",
        "leicestershire",
        "nottinghamshire",
        "derbyshire",
        "staffordshire",
        "shropshire",
        "herefordshire",
        "worcestershire",
        "west midlands",
        "lombardy",
        "lazio",
        "campania",
        "sicily",
        "veneto",
        "emilia-romagna",
        "piedmont",
        "tuscany",
        "apulia",
        "calabria",
        "sardinia",
        "liguria",
        "marche",
        "abruzzo",
        "umbria",
        "friuli-venezia giulia",
        "trentino-alto adige",
        "molise",
        "basilicata",
    }
)

CANADIAN_PROVINCES: Final[frozenset[str]] = frozenset(
    {
        "alberta",
        "british columbia",
        "manitoba",
        "new brunswick",
        "newfoundland and labrador",
        "nova scotia",
        "ontario",
        "prince edward island",
        "quebec",
        "saskatchewan",
        "yukon",
        "northwest territories",
        "nunavut",
    }
)

CANADIAN_PROVINCE_ABBREVIATIONS: Final[dict[str, str]] = {
    "AB": "Alberta",
    "BC": "British Columbia",
    "MB": "Manitoba",
    "NB": "New Brunswick",
    "NL": "Newfoundland and Labrador",
    "NS": "Nova Scotia",
    "NT": "Northwest Territories",
    "NU": "Nunavut",
    "ON": "Ontario",
    "PE": "Prince Edward Island",
    "QC": "Quebec",
    "SK": "Saskatchewan",
    "YT": "Yukon",
}

INDIAN_STATES: Final[frozenset[str]] = frozenset(
    {
        "andhra pradesh",
        "arunachal pradesh",
        "assam",
        "bihar",
        "chhattisgarh",
        "goa",
        "gujarat",
        "haryana",
        "himachal pradesh",
        "jharkhand",
        "karnataka",
        "kerala",
        "madhya pradesh",
        "maharashtra",
        "manipur",
        "meghalaya",
        "mizoram",
        "nagaland",
        "odisha",
        "punjab",
        "rajasthan",
        "sikkim",
        "tamil nadu",
        "telangana",
        "tripura",
        "uttar pradesh",
        "uttarakhand",
        "west bengal",
        "delhi",
        "jammu and kashmir",
        "ladakh",
        "puducherry",
    }
)

INDIAN_STATE_ABBR: Final[dict[str, str]] = {
    "AP": "Andhra Pradesh",
    "AR": "Arunachal Pradesh",
    "AS": "Assam",
    "BR": "Bihar",
    "CG": "Chhattisgarh",
    "GA": "Goa",
    "GJ": "Gujarat",
    "HR": "Haryana",
    "HP": "Himachal Pradesh",
    "JH": "Jharkhand",
    "KA": "Karnataka",
    "KL": "Kerala",
    "MP": "Madhya Pradesh",
    "MH": "Maharashtra",
    "MN": "Manipur",
    "ML": "Meghalaya",
    "MZ": "Mizoram",
    "NL": "Nagaland",
    "OD": "Odisha",
    "PB": "Punjab",
    "RJ": "Rajasthan",
    "SK": "Sikkim",
    "TN": "Tamil Nadu",
    "TS": "Telangana",
    "TR": "Tripura",
    "UP": "Uttar Pradesh",
    "UK": "Uttarakhand",
    "UT": "Uttarakhand",
    "WB": "West Bengal",
    "DL": "Delhi",
    "JK": "Jammu and Kashmir",
    "LA": "Ladakh",
    "PY": "Puducherry",
    "CH": "Chandigarh",
    "AN": "Andaman and Nicobar Islands",
    "DN": "Dadra and Nagar Haveli and Daman and Diu",
}

AUSTRALIAN_STATES: Final[frozenset[str]] = frozenset(
    {
        "new south wales",
        "victoria",
        "queensland",
        "south australia",
        "western australia",
        "tasmania",
        "australian capital territory",
        "northern territory",
    }
)

GERMAN_STATES: Final[frozenset[str]] = frozenset(
    {
        "baden-wurttemberg",
        "bavaria",
        "bayern",
        "berlin",
        "brandenburg",
        "bremen",
        "hamburg",
        "hesse",
        "hessen",
        "lower saxony",
        "mecklenburg-vorpommern",
        "north rhine-westphalia",
        "nordrhein-westfalen",
        "rhineland-palatinate",
        "saarland",
        "saxony",
        "sachsen",
        "saxony-anhalt",
        "schleswig-holstein",
        "thuringia",
        "thuringen",
    }
)

UK_REGIONS: Final[frozenset[str]] = frozenset(
    {
        "england",
        "scotland",
        "wales",
        "northern ireland",
        "greater london",
        "london",
    }
)

INVALID_CITY_PATTERNS: Final[list[Pattern[str]]] = [
    re.compile(r"^all\s+", re.IGNORECASE),
    re.compile(r"^flex\s*[-–]", re.IGNORECASE),
    re.compile(r"^home[-:\s]", re.IGNORECASE),
    re.compile(r"\s+or\s+", re.IGNORECASE),
    re.compile(r";", re.IGNORECASE),
    re.compile(r"^\d+\s+\w+", re.IGNORECASE),
    re.compile(r"\bstreet\b|\bst\b|\bavenue\b|\bave\b|\bblvd\b|\broad\b", re.IGNORECASE),
    re.compile(r"^\w,\s*\w", re.IGNORECASE),
    re.compile(r"^across\s+", re.IGNORECASE),
    re.compile(r"^any", re.IGNORECASE),
    re.compile(r"^beyond\s+", re.IGNORECASE),
    re.compile(r"^[a-zA-Z]$", re.IGNORECASE),
    re.compile(r"^contract", re.IGNORECASE),
    re.compile(r"^hybrid$", re.IGNORECASE),
    re.compile(r"^central\s", re.IGNORECASE),
    re.compile(r"^lt\s*-\s*", re.IGNORECASE),
    re.compile(r"^greater\s+", re.IGNORECASE),
]

INVALID_CITY_PATTERN_STRINGS: Final[list[str]] = [
    "^All ",
    "^Flex[- ]",
    "^Home[-:\\s]",
    " or ",
    "^\\d+\\s",
    "^Across ",
    "^Any",
    "^Beyond ",
    "^[a-zA-Z]$",
    "^Contract",
    "^Hybrid$",
    "^Central ",
    "^LT -",
    "^Greater ",
]

CITIES_AS_STATES: Final[dict[str, str]] = {
    "Oslo": "Oslo",
    "Brussels": "Brussels",
    "Brussels-Capital Region": "Brussels-Capital Region",
    "Budapest": "Budapest",
    "Athens": "Athens",
    "Copenhagen": "Copenhagen",
    "Helsinki": "Helsinki",
    "Lisbon": "Lisbon",
    "Prague": "Prague",
    "Vienna": "Vienna",
    "Warsaw": "Warsaw",
    "Dublin": "Dublin",
    "Rome": "Rome",
    "Milan": "Milan",
    "Barcelona": "Barcelona",
    "Madrid": "Madrid",
    "Valencia": "Valencia",
    "Munich": "Munich",
    "Hamburg": "Hamburg",
    "Frankfurt": "Frankfurt",
    "Berlin": "Berlin",
    "Cologne": "Cologne",
    "Stuttgart": "Stuttgart",
    "Zurich": "Zurich",
    "Geneva": "Geneva",
    "Bern": "Bern",
    "Basel": "Basel",
    "Lausanne": "Lausanne",
    "Lugano": "Lugano",
    "Vaud": "Vaud",
    "Zug": "Zug",
    "Stockholm": "Stockholm",
    "Gothenburg": "Gothenburg",
    "Malmo": "Malmo",
    "Amsterdam": "Amsterdam",
    "Rotterdam": "Rotterdam",
    "The Hague": "The Hague",
    "Utrecht": "Utrecht",
    "Paris": "Paris",
    "Lyon": "Lyon",
    "Marseille": "Marseille",
    "Toulouse": "Toulouse",
    "Nice": "Nice",
    "Bordeaux": "Bordeaux",
    "Krakow": "Krakow",
    "Gdansk": "Gdansk",
    "Wroclaw": "Wroclaw",
    "Bratislava": "Bratislava",
    "Ljubljana": "Ljubljana",
    "Zagreb": "Zagreb",
    "Grad Zagreb": "Grad Zagreb",
    "Sofia": "Sofia",
    "Bucharest": "Bucharest",
    "Cluj": "Cluj",
    "Graz": "Graz",
    "Salzburg": "Salzburg",
    "Riga": "Riga",
    "Vilnius": "Vilnius",
    "Tallinn": "Tallinn",
    "Harjumaa": "Harjumaa",
    "Uusimaa": "Uusimaa",
    "Kyiv": "Kyiv",
    "Kyiv City": "Kyiv City",
    "Lviv": "Lviv",
    "Belgrade": "Belgrade",
    "Sarajevo": "Sarajevo",
    "Skopje": "Skopje",
    "Tirana": "Tirana",
    "London": "London",
    "Greater London": "Greater London",
    "London, City of": "London, City of",
    "London, United Kingdom": "London, United Kingdom",
    "Manchester": "Manchester",
    "Leeds": "Leeds",
    "Glasgow": "Glasgow",
    "Edinburgh": "Edinburgh",
    "Liverpool": "Liverpool",
    "Sheffield": "Sheffield",
    "Bristol": "Bristol",
    "Bristol, City of": "Bristol, City of",
    "Newham": "Newham",
    "Ealing": "Ealing",
    "Camden": "Camden",
    "Hampshire": "Hampshire",
    "Gloucestershire": "Gloucestershire",
    "Berkshire": "Berkshire",
    "Middlesex": "Middlesex",
    "Southwark": "Southwark",
    "Hammersmith and Fulham": "Hammersmith and Fulham",
    "Midlothian": "Midlothian",
    "Abu Dhabi": "Abu Dhabi",
    "Dubai": "Dubai",
    "Riyadh": "Riyadh",
    "Jeddah": "Jeddah",
    "Doha": "Doha",
    "Kuwait City": "Kuwait City",
    "Tel Aviv": "Tel Aviv",
    "Jerusalem": "Jerusalem",
    "Haifa": "Haifa",
    "Central District": "Central District",
    "Gush Dan": "Gush Dan",
    "Tehran": "Tehran",
    "Baku": "Baku",
    "Tbilisi": "Tbilisi",
    "Yerevan": "Yerevan",
    "Cairo": "Cairo",
    "Cairo Governorate": "Cairo Governorate",
    "Giza": "Giza",
    "Istanbul": "Istanbul",
    "Ankara": "Ankara",
    "Marmara": "Marmara",
    "Seoul": "Seoul",
    "Busan": "Busan",
    "Incheon": "Incheon",
    "Gangnam": "Gangnam",
    "Gyeonggi Province": "Gyeonggi Province",
    "Tokyo": "Tokyo",
    "Osaka": "Osaka",
    "Fukuoka": "Fukuoka",
    "Kanto": "Kanto",
    "Kyoto": "Kyoto",
    "Nagoya": "Nagoya",
    "Yokohama": "Yokohama",
    "Beijing": "Beijing",
    "Shanghai": "Shanghai",
    "Shanghai Shi": "Shanghai Shi",
    "Shenzhen": "Shenzhen",
    "Hangzhou": "Hangzhou",
    "Guangzhou": "Guangzhou",
    "Chengdu": "Chengdu",
    "Hong Kong": "Hong Kong",
    "Singapore": "Singapore",
    "Taipei": "Taipei",
    "Kaohsiung": "Kaohsiung",
    "Hanoi": "Hanoi",
    "Ho Chi Minh City": "Ho Chi Minh City",
    "Ha Noi": "Ha Noi",
    "Bangkok": "Bangkok",
    "Phuket": "Phuket",
    "Kuala Lumpur": "Kuala Lumpur",
    "Penang": "Penang",
    "Jakarta": "Jakarta",
    "Surabaya": "Surabaya",
    "Bali": "Bali",
    "East Java": "East Java",
    "South Sulawesi": "South Sulawesi",
    "Manila": "Manila",
    "Cebu": "Cebu",
    "Metro Manila": "Metro Manila",
    "Manilla": "Manilla",
    "National Capital Region": "National Capital Region",
    "National Capital Region (Manila)": "National Capital Region (Manila)",
    "Mumbai": "Mumbai",
    "Delhi": "Delhi",
    "New Delhi": "New Delhi",
    "Bangalore": "Bangalore",
    "Bengaluru": "Bengaluru",
    "Chennai": "Chennai",
    "Hyderabad": "Hyderabad",
    "Pune": "Pune",
    "Kolkata": "Kolkata",
    "Ahmedabad": "Ahmedabad",
    "Jaipur": "Jaipur",
    "Gurgaon": "Gurgaon",
    "Noida": "Noida",
    "Gujarat": "Gujarat",
    "Assam": "Assam",
    "Kerala": "Kerala",
    "Tamil Nadu": "Tamil Nadu",
    "Lagos": "Lagos",
    "Nairobi": "Nairobi",
    "Nairobi Area": "Nairobi Area",
    "Johannesburg": "Johannesburg",
    "Cape Town": "Cape Town",
    "Pretoria": "Pretoria",
    "Harare": "Harare",
    "Bujumbura Mairie": "Bujumbura Mairie",
    "Sydney": "Sydney",
    "Melbourne": "Melbourne",
    "Brisbane": "Brisbane",
    "Perth": "Perth",
    "Adelaide": "Adelaide",
    "Canberra": "Canberra",
    "Auckland": "Auckland",
    "Santiago": "Santiago",
    "Buenos Aires": "Buenos Aires",
    "Lima": "Lima",
    "Bogota": "Bogota",
    "Caracas": "Caracas",
    "Carabobo": "Carabobo",
    "Magdalena": "Magdalena",
    "Brasilia": "Brasilia",
    "Salvador": "Salvador",
    "Belo Horizonte": "Belo Horizonte",
    "La Libertad": "La Libertad",
    "Arequipa": "Arequipa",
    "Lima Province": "Lima Province",
    "Biobio": "Biobio",
    "Arica Y Parinacota": "Arica Y Parinacota",
    "Mexico City": "Mexico City",
    "Ciudad de Mexico": "Ciudad de Mexico",
    "Guadalajara": "Guadalajara",
    "Monterrey": "Monterrey",
    "Nuevo Leon": "Nuevo Leon",
    "Jalisco": "Jalisco",
    "Sonora": "Sonora",
    "Chihuahua": "Chihuahua",
    "Baja California": "Baja California",
    "Toronto": "Toronto",
    "Vancouver": "Vancouver",
    "Montreal": "Montreal",
    "Calgary": "Calgary",
    "Ottawa": "Ottawa",
    "Edmonton": "Edmonton",
    "Winnipeg": "Winnipeg",
    "Quebec City": "Quebec City",
    "Boston": "Boston",
    "Chicago": "Chicago",
    "Miami": "Miami",
    "Seattle": "Seattle",
    "Denver": "Denver",
    "Atlanta": "Atlanta",
    "Dallas": "Dallas",
    "Houston": "Houston",
    "Phoenix": "Phoenix",
    "San Diego": "San Diego",
    "San Jose": "San Jose",
    "San Francisco": "San Francisco",
    "Austin": "Austin",
    "Nashville": "Nashville",
    "Portland": "Portland",
    "Las Vegas": "Las Vegas",
    "Baltimore": "Baltimore",
    "Minneapolis": "Minneapolis",
    "Detroit": "Detroit",
    "Cleveland": "Cleveland",
    "St. Louis": "St. Louis",
    "Kansas City": "Kansas City",
    "New Orleans": "New Orleans",
    "Orlando": "Orlando",
    "Tampa": "Tampa",
    "Charlotte": "Charlotte",
    "Raleigh": "Raleigh",
    "Pittsburgh": "Pittsburgh",
    "Columbus": "Columbus",
    "Indianapolis": "Indianapolis",
    "Milwaukee": "Milwaukee",
    "Sacramento": "Sacramento",
    "San Antonio": "San Antonio",
    "Fort Worth": "Fort Worth",
    "Jacksonville": "Jacksonville",
    "Louisville": "Louisville",
    "Birmingham": "Birmingham",
    "Moscow": "Moscow",
}

COUNTRIES_AS_STATES: Final[dict[str, str]] = {
    "Singapore": "Singapore",
    COUNTRY_CHINA: COUNTRY_CHINA,
    COUNTRY_UNITED_KINGDOM: COUNTRY_UNITED_KINGDOM,
    "UK": COUNTRY_UNITED_KINGDOM,
    "Hong Kong": "Hong Kong",
    COUNTRY_INDIA: COUNTRY_INDIA,
    "Ireland": "Ireland",
    "Mexico": "Mexico",
    COUNTRY_SOUTH_KOREA: COUNTRY_SOUTH_KOREA,
    "Korea": COUNTRY_SOUTH_KOREA,
    "Croatia": "Croatia",
    COUNTRY_JAPAN: COUNTRY_JAPAN,
    COUNTRY_UNITED_STATES: COUNTRY_UNITED_STATES,
    "US": COUNTRY_UNITED_STATES,
    "Vietnam": "Vietnam",
    COUNTRY_AUSTRALIA: COUNTRY_AUSTRALIA,
    "Israel": "Israel",
    "Taiwan": "Taiwan",
    COUNTRY_GERMANY: COUNTRY_GERMANY,
    COUNTRY_NETHERLANDS: COUNTRY_NETHERLANDS,
    "Kuwait": "Kuwait",
    COUNTRY_FRANCE: COUNTRY_FRANCE,
    "Argentina": "Argentina",
    "Romania": "Romania",
    "Brazil": "Brazil",
    "Colombia": "Colombia",
    "Indonesia": "Indonesia",
    "Portugal": "Portugal",
    "Saudi Arabia": "Saudi Arabia",
    "Switzerland": "Switzerland",
    "Bolivia": "Bolivia",
    "Kazakhstan": "Kazakhstan",
    "UAE": COUNTRY_UAE,
    "Thailand": "Thailand",
    "Bosnia and Herzegovina": "Bosnia and Herzegovina",
    "Norway": "Norway",
    "Sweden": "Sweden",
    "Denmark": "Denmark",
    "Finland": "Finland",
    "Poland": "Poland",
    "Austria": "Austria",
    COUNTRY_CZECHIA: COUNTRY_CZECHIA,
    "Czech Republic": COUNTRY_CZECHIA,
    "Hungary": "Hungary",
    "Greece": "Greece",
    "Philippines": "Philippines",
    "Malaysia": "Malaysia",
    "New Zealand": "New Zealand",
    "South Africa": "South Africa",
    "Nigeria": "Nigeria",
    "Kenya": "Kenya",
    "Egypt": "Egypt",
    COUNTRY_TURKEY: COUNTRY_TURKEY,
    "Pakistan": "Pakistan",
    "Bangladesh": "Bangladesh",
    "Chile": "Chile",
    "Peru": "Peru",
    "Ecuador": "Ecuador",
    "Venezuela": "Venezuela",
    COUNTRY_CANADA: COUNTRY_CANADA,
    "England": COUNTRY_UNITED_KINGDOM,
    "Scotland": COUNTRY_UNITED_KINGDOM,
    "Wales": COUNTRY_UNITED_KINGDOM,
    "Northern Ireland": COUNTRY_UNITED_KINGDOM,
}

STATE_MAPPINGS: Final[dict[str, str | None]] = {
    "Washington D.C.": "District of Columbia",
    "Washington, D.C.": "District of Columbia",
    "Washington D.C": "District of Columbia",
    "District Of Columbia": "District of Columbia",
    "New York State": "New York",
    "Washington State": "Washington",
    "NY": "New York",
    "California, Washington": None,
    "Seattle, Washington": "Washington",
    "San Francisco, Seattle": None,
    "Sao Paulo": "Sao Paulo",
    "Quebec": "Quebec",
    "Cordoba": "Cordoba",
    "Karnataka": "Karnataka",
    "Maharashtra": "Maharashtra",
    "Telangana": "Telangana",
    "Rajasthan": "Rajasthan",
    "Mexico": "Mexico",
    "Nuevo Leon": "Nuevo Leon",
    "Ceara": "Ceara",
    "Espirito Santo": "Espirito Santo",
    "Krakow": "Krakow",
    "Ile de France": "Ile-de-France",
    "Ile-De-France": "Ile-de-France",
    "Hauts-De-France": "Hauts-de-France",
    "Pays De La Loire": "Pays de la Loire",
    "Bretagne": "Brittany",
    "Brittany": "Brittany",
    "Alsace": "Grand Est",
    "Grand Est": "Grand Est",
    "Occitanie": "Occitanie",
    "Bayern": "Bavaria",
    "Nordrhein-Westfalen": "North Rhine-Westphalia",
    "Northrhine-Westfalia": "North Rhine-Westphalia",
    "North Rhine Westphalia": "North Rhine-Westphalia",
    "Thuringen": "Thuringia",
    "Toscana": "Tuscany",
    "Milano": None,
    "Roma": None,
    "Firenze": None,
    "Florence": None,
    "Rome": None,
    "Milan": None,
    "Comunidad de Madrid": None,
    "Community of Madrid": None,
    "Comunidad Valenciana": "Valencia",
    "Pais Vasco": "Basque Country",
    "Islas Baleares": "Balearic Islands",
    "Murcia": "Murcia",
    "Santander": None,
    "Rio De Janeiro": "Rio de Janeiro",
    "Rio Grande Do Norte": "Rio Grande do Norte",
    "Rio Grande Do Sul": "Rio Grande do Sul",
    "Ciudad de Mexico": None,
    "Mexico City": None,
    "Newfoundland And Labrador": "Newfoundland and Labrador",
    "London": None,
    "London, City of": None,
    "London, United Kingdom": None,
    "Greater London": None,
    "England": None,
    "Scotland": None,
    "Wales": None,
    "Northern Ireland": None,
    "Berkshire": None,
    "Gloucestershire": None,
    "Hampshire": None,
    "Middlesex": None,
    "Midlothian": None,
    "Camden": None,
    "Ealing": None,
    "Newham": None,
    "Southwark": None,
    "Hammersmith and Fulham": None,
    "Bristol": None,
    "Bristol, City of": None,
    "Leeds": None,
    "Manchester": None,
    "Liverpool": None,
    "Sheffield": None,
    "Glasgow": None,
    "Edinburgh": None,
    "Noord-Holland": "North Holland",
    "North Holland": "North Holland",
    "North Brabant": "North Brabant",
    "South Holland": "South Holland",
    "NSW": "New South Wales",
    "Victoria": "Victoria",
    "Queensland": "Queensland",
    "South Australia": "South Australia",
    "Western Australia": "Western Australia",
    "Tasmania": "Tasmania",
    "Australian Capital Territory": "Australian Capital Territory",
    "Northern Territory": "Northern Territory",
    "Canberra": None,
    "Manilla": None,
    "Ha Noi": None,
    "Karnaka": "Karnataka",
    "Guateng": "Gauteng",
    "Tokyo": None,
    "Jakarta": None,
    "Singapore": None,
    "Hong Kong": None,
    "Seoul": None,
    "Shanghai": None,
    "Beijing": None,
    "Shenzhen": None,
    "Dubai": None,
    "Abu Dhabi": None,
    "Amsterdam": None,
    "Rotterdam": None,
    "Brussels": None,
    "Brussels-Capital Region": None,
    "Paris": None,
    "Berlin": None,
    "Berlin-Brandenburg": None,
    "Berlin/Brandenburg": None,
    "Berlin/ Brandenburg metropolitan region": None,
    "Munich": None,
    "Hamburg": None,
    "Frankfurt": None,
    "Vienna": None,
    "Zurich": None,
    "Geneva": None,
    "Bern": None,
    "Lugano": None,
    "Vaud": None,
    "Zug": None,
    "Stockholm": None,
    "Oslo": None,
    "Copenhagen": None,
    "Helsinki": None,
    "Lisbon": None,
    "Prague": None,
    "Warsaw": None,
    "Budapest": None,
    "Athens": None,
    "Dublin": None,
    "Sydney": None,
    "Melbourne": None,
    "Brisbane": None,
    "Perth": None,
    "Auckland": None,
    "Toronto": None,
    "Vancouver": None,
    "Montreal": None,
    "Calgary": None,
    "Ottawa": None,
    "Mexico City": None,
    "Birmingham": None,
    "Boston": None,
    "Miami": None,
    "Delhi": None,
    "Buenos Aires": None,
    "Santiago": None,
    "Lima": None,
    "Bogota": None,
    "Tel Aviv": None,
    "Jerusalem": None,
    "Riyadh": None,
    "Riyadh Province": None,
    "Cairo": None,
    "Lagos": None,
    "Nairobi": None,
    "Cape Town": None,
    "Johannesburg": None,
    "Bangkok": None,
    "Kuala Lumpur": None,
    "Manila": None,
    "Ho Chi Minh City": None,
    "Hanoi": None,
    "Taipei": None,
    "Kyiv": None,
    "Riga": None,
    "Vilnius": None,
    "Ljubljana": None,
    "Zagreb": None,
    "Grad Zagreb": None,
    "Bratislava": None,
    "Belgrade": None,
    "Tehran": None,
    "Tbilisi": None,
    "Sofia": None,
    "Krakow": None,
    "New Delhi": None,
    "Hangzhou": None,
    "Qingdao": None,
    "Osaka": None,
    "Giza": None,
    "Catanzaro": None,
    "Cordoba": None,
    "Barcelona": None,
    "Madrid": None,
    "Harare": None,
    "Lefkosia": None,
    "Limassol": None,
    "Yokne'am": None,
    "Bnei Brak": None,
    "Gush Dan": None,
    "Heredia": None,
    "Ankara": None,
    "Livadia": None,
    "Angre": None,
    "Baki": None,
    "Arequipa": None,
    "Faro": None,
    "Santander": None,
    "Lugano": None,
    "Shanghai Shi": None,
    "East China": None,
    "Kanto": None,
    "Tokyo Metropolis": None,
    "Gyeonggi Province": None,
    "Central Singapore": None,
    "Orchard Road": None,
    "National Capital Region": None,
    "National Capital Region (Manila)": None,
    "Capital Region": None,
    COUNTRY_AUSTRALIA: None,
    COUNTRY_CHINA: None,
    COUNTRY_GERMANY: None,
    COUNTRY_FRANCE: None,
    COUNTRY_INDIA: None,
    "Indonesia": None,
    "Ireland": None,
    "Israel": None,
    COUNTRY_JAPAN: None,
    "Korea": None,
    COUNTRY_NETHERLANDS: None,
    "Portugal": None,
    "Saudi Arabia": None,
    COUNTRY_SOUTH_KOREA: None,
    "Switzerland": None,
    "Taiwan": None,
    "UAE": None,
    "UK": None,
    COUNTRY_UNITED_KINGDOM: None,
    COUNTRY_UNITED_STATES: None,
    "US": None,
    "Vietnam": None,
    "Argentina": None,
    "Bolivia": None,
    "Brazil": None,
    "Mexico": None,
    "Colombia": None,
    "Kuwait": None,
    "Kazakhstan": None,
    "Romania": None,
    "Thailand": None,
    "Croatia": None,
    COUNTRY_CANADA: None,
    COUNTRY_TURKEY: None,
    "Norway": None,
    "Sweden": None,
    "Denmark": None,
    "Finland": None,
    "Poland": None,
    "Austria": None,
    COUNTRY_CZECHIA: None,
    "Czech Republic": None,
    "Hungary": None,
    "Greece": None,
    "Philippines": None,
    "Malaysia": None,
    "New Zealand": None,
    "South Africa": None,
    "Nigeria": None,
    "Kenya": None,
    "Egypt": None,
    "Pakistan": None,
    "Bangladesh": None,
    "Chile": None,
    "Peru": None,
    "Ecuador": None,
    "Venezuela": None,
    "Bosnia and Herzegovina": None,
    "Canada ": None,
    "Jakarta ": None,
    "Tokyo ": None,
    "Remote": None,
    "Hybrid": None,
    "EU": None,
    "Europe": None,
    "United States & Canada": None,
    "United States Minor Outlying Islands": None,
    "FORA, Albert House, 256-260 Old Street, London, EC1V 9DD": None,
    "Kleine-Gartmanplantsoen 21, 1017RP, Amsterdam": None,
    "Gangnam": None,
    "New South Wales": "New South Wales",
}

US_STATE_TO_ABBR: Final[dict[str, str]] = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
}

ABBR_TO_STATE: Final[dict[str, str]] = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming",
    "DC": "District of Columbia",
    "AB": "Alberta",
    "BC": "British Columbia",
    "MB": "Manitoba",
    "NB": "New Brunswick",
    "NL": "Newfoundland and Labrador",
    "NS": "Nova Scotia",
    "NT": "Northwest Territories",
    "NU": "Nunavut",
    "ON": "Ontario",
    "PE": "Prince Edward Island",
    "QC": "Quebec",
    "SK": "Saskatchewan",
    "YT": "Yukon",
}

INVALID_STATES: Final[frozenset[str]] = frozenset(
    {
        "United States & Canada",
        "United States Minor Outlying Islands",
        "EU",
        "Europe",
        "Remote",
        "Hybrid",
        "Any",
        "Various",
        "Multiple",
        "TBD",
        "N/A",
        "FORA, Albert House, 256-260 Old Street, London, EC1V 9DD",
        "Kleine-Gartmanplantsoen 21, 1017RP, Amsterdam",
        "Gangnam",
        "Orchard Road",
    }
)
