use_default_settings:
  engines:
    keep_only:
      - google
      - presearch

general:
  debug: false
  instance_name: "SearXNG"
  enable_metrics: true

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "auto"
  formats:
    - html
    - json

server:
  base_url: false
  limiter: false
  public_instance: false
  image_proxy: false
  http_protocol_version: "1.1"
  method: "GET"
  secret_key: "change-this-secret-key"

engines:
  - name: google
    disabled: false
    timeout: 10.0

  - name: presearch
    disabled: false
    timeout: 10.0

ui:
  default_theme: simple
  default_locale: ""
  theme_args:
    simple_style: auto

preferences:
  lock: []

plugins:
  searx.plugins.calculator.SXNGPlugin:
    active: true
  searx.plugins.hash_plugin.SXNGPlugin:
    active: true
  searx.plugins.self_info.SXNGPlugin:
    active: true
  searx.plugins.unit_converter.SXNGPlugin:
    active: true
  searx.plugins.time_zone.SXNGPlugin:
    active: true
  searx.plugins.tracker_url_remover.SXNGPlugin:
    active: true
